repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.81.0"
    hooks:
      - id: terraform_fmt
        args:
          - "--args=-diff"
          - "--args=-recursive"
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_validate
        args:
          - "--hook-config=--retry-once-with-cleanup=true"
          - "--tf-init-args=-backend=false"
      - id: terraform_docs
        args:
          - "--hook-config=--path-to-file=./README.md"
          - "--hook-config=--add-to-existing-file=true"
